language: java
sudo: false
install: true
addons:
  sonarqube:
    organization: "msgjt-github"
    branches:
      - master
      - develop
script:
  - sonar-scanner
jdk:
  - oraclejdk8
script:
  # the following command line builds the project, runs the tests with coverage and then  execute the SonarQube analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
